services:
  - type: web
    name: hybrid-recommendation-engine
    env: python
    buildCommand: pip install -r requirements-deploy.txt
    startCommand: uvicorn api.app:app --host 0.0.0.0 --port 8080
    plan: free
    envVars:
      - key: PORT
        value: 8080
